#!/bin/bash

script_dir=$(dirname $0)
hook_name=$(basename $0)

if [[ `whoami` == "root" ]]; then
   echo "Skipping pre-commit hooks for git because you are root!"
   exit 0
fi

# Go over subhooks
for subhook in $(ls $script_dir/$hook_name.d); do
  echo "$hook_name hook> Executing $subhook"
  $script_dir/$hook_name.d/$subhook
  if [[ $? != 0 ]]; then
    exit 1
  fi
done
